### ISSUE TITLE
Only first image is working, other images failed.

### ISSUE THREAD

**Issue by jodo1** [grzegorzekkk/SketchMap#1]
For 1.12. First image is OK, but then:
"[CHAT] [SketchMap] You have reached your limit for number of sketchmaps owned. If you want to make another, delete one of your existing maps."
If I edit config file and restart, server stuck on load Sketchmap, CPU run on 100% and server not responding.

**Comment by grzegorzekkk** [comment]
I will look into this in a few days.
EDIT: Does any errors appears in server console? If yes, could you post them?

**Comment by grzegorzekkk** [comment]
I could not reproduce that bug. 
Please provide sketchmap version, server version, sketchmap config directory and error stacktraces from console if there were any.

**Comment by jodo1** [comment]
I try totally reinstall my test server, with only one plugin, SketchMap 1.4.3.
Version: Spigot 1.12 Build 201708040854, (last 1.12 version)
Plugin unfortunately not started.

[20:20:42 INFO]: [SketchMap] Enabling SketchMap v1.4.3
[20:20:42 ERROR]: Error occurred while enabling SketchMap v1.4.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/milkbowl/vault/permission/Permission
at com.mcplugindev.slipswhitley.sketchmap.SketchMapUtils.setupPermissions(SketchMapUtils.java:87) ~[?:?]
at com.mcplugindev.slipswhitley.sketchmap.SketchMapPlugin.onEnable(SketchMapPlugin.java:25) ~[?:?]
at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:337) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:402) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:374) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:323) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:421) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:382) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:337) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:272) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:544) [minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at java.lang.Thread.run(Thread.java:745) [?:1.8.0_74]
Caused by: java.lang.ClassNotFoundException: net.milkbowl.vault.permission.Permission
at java.net.URLClassLoader.findClass(URLClassLoader.java:381) ~[?:1.8.0_74]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[minecraft_server.jar:git-Spigot-596221b-9a1fc1e]
at java.lang.ClassLoader.loadClass(ClassLoader.java:424) ~[?:1.8.0_74]
at java.lang.ClassLoader.loadClass(ClassLoader.java:357) ~[?:1.8.0_74]
... 13 more

**Comment by jodo1** [comment]
I totally reinstall my test server (czech server hosting fakaheda), with only two plugins, SketchMap 1.4.3 (downloaded now from this page) and Vault.
Server : Spigot 1.12 Build 201708040854 (last develop version)
Unfortunately, no succes.
Plugin started OK:
[SketchMap] Default max sketchmap dimensions: 10x10
[20:40:26 INFO]: [SketchMap] Default privacy level: Public
[20:40:26 INFO]: [SketchMap] Default max owned maps: 0
[20:40:26 INFO]: [SketchMap] Finished! 0 sketchmaps loaded

First placed image is OK, but another image failed with this:

[CHAT] [SketchMap] You have reached your limit for number of sketchmaps owned. If you want to make another, delete one of your existing maps.

If I change config:
default-max-owned-maps: 0
to:
default-max-owned-maps: 3
server stop responding, load 100%.

**Comment by grzegorzekkk** [comment]
[This](https://github.com/grzegorzekkk/SketchMap/releases/download/1.4.4/SketchMap-1.4.4.jar) release solves 100% CPU and loading problem, but sadly you should recreate all of your sketchmaps.

Permissions are not fixed yet, I will fix them in a free time :)

**Comment by grzegorzekkk** [comment]
If you want to allow your players having more sketchmaps than limit specify, give them permissions:
sketchmap.ownlimit.defaultexempt
sketchmap.ownlimit.#
where # is number of sketchmaps limited by these permissions.
